[package]
name = "Nito"
version = "0.1.0"
edition = "2021"

[lib]
name = "nito"
path = "src/core/lib.rs"

[[bin]]
name = "server"

[dependencies]
toml = "0.8.6"
serde = { version = "1.0.190", features = ["derive"] }
